import React from 'react';
import { SubsystemHealth } from '../../types/uyaree';
import { BrainCircuit, CheckCircle2, AlertTriangle, ShieldCheck, ArrowRight, HelpCircle, Activity, Thermometer, Gauge } from 'lucide-react';

interface ExplainableAIProps {
  subsystem: SubsystemHealth | null;
  onOpenMaintenance: () => void;
}

export const ExplainableAI: React.FC<ExplainableAIProps> = ({
  subsystem,
  onOpenMaintenance,
}) => {
  const engine2 = subsystem || {
    id: 'engine2',
    name: 'Engine 2 (Starboard Turbofan)',
    health: 76,
    status: 'ATTENTION',
    risk: 'HIGH',
    metrics: { temperature: 704, vibration: 1.8, pressure: 38, rpm: 12580 }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-slate-900 via-cyan-950/40 to-slate-900 border border-slate-800 rounded-2xl p-6 relative overflow-hidden tech-corner">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2.5 rounded-xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/40">
            <BrainCircuit className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] font-mono text-cyan-400 uppercase tracking-widest font-semibold block">Transparent AI Decision Support</span>
            <h1 className="text-2xl font-bold text-slate-100 font-mono">Explainable AI Diagnostics</h1>
          </div>
        </div>
        <p className="text-xs text-slate-400 max-w-2xl">
          Every health prediction and degradation alert generated by UYAREE provides explicit, auditable rationale answering What, Why, How Confident, and What Next.
        </p>
      </div>

      {/* Main 4-Question Explainable Framework Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* 1. WHAT? */}
        <div className="bg-slate-900/80 backdrop-blur-md rounded-2xl border border-slate-800 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-3 text-cyan-400 font-mono text-xs font-bold uppercase tracking-wider">
              <span className="w-6 h-6 rounded-lg bg-cyan-500/20 flex items-center justify-center text-cyan-300 font-extrabold">1</span>
              <span>WHAT IS HAPPENING?</span>
            </div>
            <h3 className="text-lg font-bold text-slate-100 font-mono mb-2">
              Engine 2 Degradation Risk Alert
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              UYAREE health intelligence engine detected an abnormal degradation pattern in <strong className="text-amber-400">Engine 2 (Starboard Turbofan)</strong>. Current health score is <strong className="text-amber-400">76%</strong> with risk shifting from MEDIUM to HIGH under stress.
            </p>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs font-mono">
            <span className="text-slate-400">Target System:</span>
            <span className="text-cyan-300 font-bold">Engine 2 (UY-001)</span>
          </div>
        </div>

        {/* 2. WHY? */}
        <div className="bg-slate-900/80 backdrop-blur-md rounded-2xl border border-slate-800 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-3 text-amber-400 font-mono text-xs font-bold uppercase tracking-wider">
              <span className="w-6 h-6 rounded-lg bg-amber-500/20 flex items-center justify-center text-amber-300 font-extrabold">2</span>
              <span>WHY IS IT HAPPENING?</span>
            </div>
            <h3 className="text-lg font-bold text-slate-100 font-mono mb-2">
              Multi-Sensor Feature Attribution
            </h3>
            <div className="space-y-2 font-mono text-xs mb-3">
              <div className="flex items-center justify-between p-2 bg-slate-950/60 rounded-lg border border-slate-800">
                <span className="flex items-center gap-1.5 text-slate-300"><Activity className="w-3.5 h-3.5 text-red-400" /> Vibration:</span>
                <span className="text-red-400 font-bold">1.8g (+18% trend)</span>
              </div>
              <div className="flex items-center justify-between p-2 bg-slate-950/60 rounded-lg border border-slate-800">
                <span className="flex items-center gap-1.5 text-slate-300"><Thermometer className="w-3.5 h-3.5 text-amber-400" /> Temperature:</span>
                <span className="text-amber-400 font-bold">704°C (+9% trend)</span>
              </div>
              <div className="flex items-center justify-between p-2 bg-slate-950/60 rounded-lg border border-slate-800">
                <span className="flex items-center gap-1.5 text-slate-300"><Gauge className="w-3.5 h-3.5 text-sky-400" /> Oil Pressure:</span>
                <span className="text-sky-400 font-bold">38 psi (-7% drop)</span>
              </div>
            </div>
          </div>

          <p className="text-[11px] text-slate-400 leading-relaxed">
            Root cause analysis identifies N1 rotor shaft bearing clearance wear causing secondary thermal buildup.
          </p>
        </div>

        {/* 3. HOW CONFIDENT? */}
        <div className="bg-slate-900/80 backdrop-blur-md rounded-2xl border border-slate-800 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-3 text-emerald-400 font-mono text-xs font-bold uppercase tracking-wider">
              <span className="w-6 h-6 rounded-lg bg-emerald-500/20 flex items-center justify-center text-emerald-300 font-extrabold">3</span>
              <span>HOW CONFIDENT IS THE MODEL?</span>
            </div>
            <div className="flex items-center justify-between mb-3">
              <div>
                <span className="text-3xl font-extrabold font-mono text-emerald-400">91%</span>
                <span className="text-xs font-mono text-slate-400 block">AI CONFIDENCE SCORE</span>
              </div>
              <span className="px-3 py-1 rounded-full text-xs font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                HIGH MODEL CERTAINTY
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              Trained on simulated historical turbofan sensor telemetry datasets. Anomaly score verified via XGBoost & Random Forest ensemble evaluation.
            </p>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-800/80 text-[11px] font-mono text-slate-400">
            Model Type: Telemetry Anomaly & RUL Estimator v1.4
          </div>
        </div>

        {/* 4. WHAT NEXT? */}
        <div className="bg-slate-900/80 backdrop-blur-md rounded-2xl border border-cyan-500/40 p-6 flex flex-col justify-between glow-cyan">
          <div>
            <div className="flex items-center gap-2 mb-3 text-cyan-400 font-mono text-xs font-bold uppercase tracking-wider">
              <span className="w-6 h-6 rounded-lg bg-cyan-500/20 flex items-center justify-center text-cyan-300 font-extrabold">4</span>
              <span>WHAT NEXT? (RECOMMENDED ACTION)</span>
            </div>
            <h3 className="text-lg font-bold text-slate-100 font-mono mb-2">
              Schedule Engineering Inspection
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed mb-4">
              Schedule targeted borescope inspection of Engine 2 turbine blades & rotor bearing within <strong className="text-cyan-300 font-bold">18 flight cycles</strong> (estimated Remaining Useful Life).
            </p>
          </div>

          <button
            onClick={onOpenMaintenance}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-mono font-bold text-xs uppercase tracking-wider transition-all"
          >
            <span>View Prioritized Maintenance Cards</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
